# Generated by Django 5.2.1 on 2025-08-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='business_licenses/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='drivers_license',
            field=models.FileField(blank=True, null=True, upload_to='drivers_licenses/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_type_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
